package com.xiao.blog.model;

import lombok.Data;

import java.io.Serializable;
@Data
public class Categories implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_categories.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_categories.text
     *
     * @mbggenerated
     */
    private String text;


    private Integer userId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_categories.publishdate
     *
     * @mbggenerated
     */
    private String publishdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_categories.updatedate
     *
     * @mbggenerated
     */
    private String updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_categories.icon
     *
     * @mbggenerated
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blog_categories
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;


}