package com.xiao.blog.model;

import lombok.Data;

import java.io.Serializable;

@Data
public class Label implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_label.name
     *
     * @mbggenerated
     */
    private String name;

    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_label.publishdate
     *
     * @mbggenerated
     */
    private String publishdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_label.updatedate
     *
     * @mbggenerated
     */
    private String updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blog_label
     *
     * @mbggenerated
     */



}