package com.xiao.blog.mapper;

import com.xiao.blog.model.Categories;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface CategoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_categories
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_categories
     *
     * @mbggenerated
     */
    int insert(Categories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_categories
     *
     * @mbggenerated
     */
    Categories selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_categories
     *
     * @mbggenerated
     */
    List<Categories> selectAll(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_categories
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Categories record);
}